# Generated by Django 3.0.6 on 2022-03-30 16:19

import SmartDjango.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('category', SmartDjango.models.fields.CharField(max_length=128)),
                ('subcategory', SmartDjango.models.fields.CharField(max_length=128)),
                ('nid', SmartDjango.models.fields.CharField(db_index=True, max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
